name: scan-ip

on:
  workflow_dispatch:  # 手动触发
  schedule:
    # 每天凌晨2点运行（UTC时间，北京时间10点）
    - cron: '0 2 * * *'

jobs:
  scan-ip:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: 安装依赖
      run: pip install requests
        
    - name: 创建目录结构
      run: |
        
    - name: 运行IP扫描
      run: python Hotel/scan_ip.py
        
    - name: Commit and push changes
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "更新扫描ip"
          git push --force origin main 
